[package]
version = "1.0.3" # Semantic Versioning is used: https://semver.org/

# These fields are used primarily for display in the extension browser UI.
title = "Custom ROS2 Msgs OGN Extension"
description = "Create a ROS2 C++ node for Custom Msgs as OmniGraph"
category = "Custom"
keywords = ["custom", "C++", "cpp", "Graph", "Node", "OmniGraph"]
icon = "data/icon.png"
preview_image = "data/preview.png"
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"


[dependencies]
"omni.graph.core" = {}
"omni.graph.tools" = {}

[[python.module]]
name = "omni.custom.cpp.ogn_ros"

[[native.plugin]]
path = "bin/*.plugin"

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
